### ISSUE TITLE
Is this library support MaterialDrawer's badge ?

### ISSUE THREAD

**Issue by korrio** [mikepenz/Crossfader#1]
Can I attach badge on each icon ?
![screenshot](https://raw.githubusercontent.com/mikepenz/Crossfader/develop/DEV/screenshots/screenshot1_small.png)

**Comment by mikepenz** [comment]
@korrio this library is just about the view which allows to do the crossfade effect. It will be included in the upcoming v4.0.0 of the MaterialDrawer. There's a testing issue opened at the MaterialDrawer repo at the moment. Can you please note this thing over there? Its a really awesome idea to support badges for the MiniDrawer too ;) https://github.com/mikepenz/MaterialDrawer

https://github.com/mikepenz/MaterialDrawer/issues/487
