### ISSUE TITLE
Clicks are fall-thru to the first view when crossfader is in closed state

### ISSUE THREAD

**Issue by dstd** [mikepenz/Crossfader#10]
Clicks are fall-thru to the first view when crossfader is in closed state, and leads to unexpected items switching. Not sure that it's `Crossfader`'s issue, but it takes the place only with it.

Here is a demonstration on MaterialDrawer stock example app:
https://www.youtube.com/watch?v=VbMWsNzhZOQ

**Comment by mikepenz** [comment]
@dstd making the right area `clickable=true` should consume the event so it should no longer pass it through to the view behind.

**Comment by dstd** [comment]
@mikepenz thank you. I've fixed that by managing subview's visibility in `PanelSlideListener`, but your suggestion looks simplier

**Comment by mikepenz** [comment]
@dstd great :)
