### ISSUE TITLE
How can i hide the panel?

### ISSUE THREAD

**Issue by arthursz** [mikepenz/Crossfader#11]
Hi!

How can a hide the panel completely from the view? I am trying using setVisibility(View.GONE) but the right panel won't go fullscreen it acts like the drawer was still there.

Thanks!

**Comment by mikepenz** [comment]
@arthursz this is not possible with the `Crossfader` it is not meant for such a usecase. Perhaps you should directly check the `SlidingPaneLayout`

**Comment by arthursz** [comment]
Ok, Thanks!
