### ISSUE TITLE
Unresolved CrossfaderWrapper

### ISSUE THREAD

**Issue by AliAkhgar** [mikepenz/Crossfader#12]
hi, i use this library for MaterialDrawer and i use the samples but cant resolve CrossfaderWrapper!
help me please...

**Comment by mikepenz** [comment]
@theAliAkhgar you have to implement it. As I use an interface internally to allow other implementations too:

https://github.com/mikepenz/Crossfader/blob/develop/app/src/main/java/com/mikepenz/crossfader/app/util/CrossfadeWrapper.java
