### ISSUE TITLE
Is there anyway to make a three-state cross fader?

### ISSUE THREAD

**Issue by prateek-dhanuka** [mikepenz/Crossfader#13]
I am using the material drawers mini drawer and was wondering if there was anyway to make something like a thee-state cross fader, Something along the lines of having an expanded complete drawer of say width 300, a semi-closed state of the mini drawer say width 70, and a completely closed state of width 0. Can I make this? By something like maybe nesting two cross faders or some native method?

**Comment by mikepenz** [comment]
@prateek-dhanuka this project does not allow this. And the `SlidingPaneLayout` this project bases on neither. 

I guess you have to implement your own custom layout to support this
