### ISSUE TITLE
Not enough information to infer parameter T in constructor Crossfader

### ISSUE THREAD

**Issue by lucaskuan** [mikepenz/Crossfader#15]
When I try to instantiate the Crossfader in kotlin, I got this following error
`Error:(40, 43) Type inference failed: Not enough information to infer parameter T in constructor Crossfader<T : SlidingPaneLayout!>() where T : ICrossFadeSlidingPaneLayout!
Please specify it explicitly.`
Please help out how to use crossfader in kotlin. Thank you.

**Comment by harshasuda** [comment]
have you found any solution for this?..
