### ISSUE TITLE
Cannot Find Interface for Crossfader

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/Crossfader#2]
Cannot Find Interface for Crossfader

**Comment by mikepenz** [comment]
@patelakshay13890 what do you mean?

**Comment by mikepenz** [comment]
The `ICrossfader` interface comes from the v4.0.0 (which is currently in testing) MaterialDrawer
https://github.com/mikepenz/Crossfader/blob/develop/app/src/main/java/com/mikepenz/crossfader/app/util/CrossfadeWrapper.java

--> https://github.com/mikepenz/MaterialDrawer/issues/487
