### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/Crossfader#4]
I'm trying to implement Crossfader in my application but I get this error: "The specified child already has a parent. You must call removeView() on the child's parent first."

Here: 

``` java
crossFader = new Crossfader()
                .withContent(findViewById(R.id.crossfade_content))
                .withFirst(result.getSlider(), firstWidth)
                .withSecond(miniResult.build(this), secondWidth)
                .withSavedInstance(savedInstanceState)
                .build();
```

**Comment by mikepenz** [comment]
@EpsilonOrionis can you please provide some more code. How does your layout of this activity look like? Do you do any other stuff before?

**Comment by EpsilonOrionis** [comment]
Yes, I do. I have an activity (Main) where I show the cross fader, but this activity has a ViewPager to show fragments. Could this project structure cause the error?

**Comment by mikepenz** [comment]
@EpsilonOrionis please provide some more code and the layout. I really can't tell more without additional details

**Comment by EpsilonOrionis** [comment]
Sorry, my fault again... :D
