### ISSUE TITLE
Swiping like in Gmail

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/Crossfader#5]
I've setup the MiniDrawer and my view on the right-hand-side is a ViewPager with TabLayout. Right swipes are consumed by the minidrawer(crossfader) which breaks the view pager.

Can crossfader library be updated to support swiping like in gmail?
(1).When drawer is closed, swiping area for opening is left-pane
(2).When drawer is opened, swiping area for closing is right-pane

I have selected swiping area in screenshots.

![screenshot_20151030-153046](https://cloud.githubusercontent.com/assets/1249919/10891128/930b52e6-81b5-11e5-9eae-3157f469cc63.png)
![screenshot_20151030-153423](https://cloud.githubusercontent.com/assets/1249919/10891127/930a326c-81b5-11e5-9770-8b5c1c3f0f9f.png)

P.S.
Now I can only disable swiping when drawer is closed, and enable swiping when opened. This way I achieve the (2). Crossfader disables full swiping, it would be great to have also methods like enable/disable ONLY second pane swiping.

**Comment by mikepenz** [comment]
as mentinoed by you in the other ticket:

---

@mikepenz Ok, I just copied the issue there. Library will be more flexible with this. 
It seems that changes should be done here

``` java
  @Override
    public boolean onTouchEvent(MotionEvent ev) {
        return mCanSlide && super.onTouchEvent(ev);
    }
```

Based on touch region swipe should be enabled or disabled

**Comment by mikepenz** [comment]
If i add an api that you can provide an extended variant of the `SlidingPaneLayout` would it solve the issue for you?

**Comment by androideveloper** [comment]
Not sure. If you add method to enable/disable only right pane swipe,that will solve.

**Comment by mikepenz** [comment]
@androideveloper i have added a new option to provide a custom `CrossFadeSlidingPaneLayout` implementation to the `Crossfader`

You will have to do 3 things. 
- Create a Custom`CrossFadeSlidingPaneLayout` implementation by extending the existing `CrossFadeSlidingPaneLayout` or by creating a new class which `extends SlidingPaneLayout` and  `implements ICrossFadeSlidingPaneLayout`
- Create a new base_layout, based on the `crossfader_base.xml`
- Provide the custom base_layout via the `.withBaseLayout()` method

If you find a nice implementation for the above feature, i would be happy about a pull request.

**Comment by androideveloper** [comment]
Ok, great! Thanks fro new api.
I have implemented this feature and sent pull request.

https://youtu.be/FiKUSBMOqGc

**Comment by mikepenz** [comment]
Thank you so much ;). merged. will release a new version later today ;)

**Comment by mikepenz** [comment]
It's in v1.3.0 ;)

**Comment by androideveloper** [comment]
@mikepenz thanks. But it seems we have some issue. We will try to fix

**Comment by mikepenz** [comment]
ok?
