### ISSUE TITLE
Uncolored area while in transition

### ISSUE THREAD

**Issue by dstd** [mikepenz/Crossfader#8]
I'm using MiniDrawer feature of MaterialDrawer, and I need to change a color of the drawer.

I've changed `material_drawer_background` color value but faced with two issues:
1. In mini-mode the mini-drawer is still plain white. This issue was fixed with `miniDrawerView.setBackgroundColor`
2. While a transition is in progress there is an uncolored gap between mCrossFadeSecond and mCrossFadeContainer (in terms of Crossfader's source code)

Could you please point me towards the most elegant solution of this issue?
`Crossfader` provides no access to the `mCrossFadePanel` out of the box. The duct tape solution that helps with the issue is:

``` java
    val crossFader = Crossfader<CrossFadeSlidingPaneLayout>()
            .withContent(findViewById(R.id.main_content))
            .withFirst(drawer.slider, widthExpanded)
            .withSecond(miniDrawerView, widthCollapsed)
            .withSavedInstance(savedInstanceState)
            .build()

    (miniDrawerView.parent.parent as View).setBackgroundColor(someBackgroundColor)
```

**Comment by mikepenz** [comment]
You coudl get the `SlidingPaneLayout` https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/Crossfader.java#L235

and you can get the `Panel` just by doing this:

``` java
mCrossFadeSlidingPaneLayout.findViewById(R.id.panel)
```
