### ISSUE TITLE
View Open from Right to Left

### ISSUE THREAD

**Issue by arthursz** [mikepenz/Crossfader#9]
Hi! 

It's there any way to create a view that opens from right to left?

Thanks

**Comment by mikepenz** [comment]
@arthursz if your application is in RTL mode it will be in the opposite automatically. 

If you have a normal application without RTL text and want to have it in the opposite way. I expect it would require some changes in the `SlidingPaneLayout` or the `CrossfadeSlidingPaneLayout`. 
I do not know if the `SlidingPaneLayout` supprots something like this by default. 
But you can have a look at the source here: https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/view/CrossFadeSlidingPaneLayout.java

**Comment by arthursz** [comment]
Thanks!!
